import crypto from 'node:crypto'

/**
 * Reset links are generated by an admin and handed to the person directly —
 * there is no mail provider in this stack, and a self-service "email me a
 * link" flow without one would let anyone reset anyone. `resetLinkFor` is the
 * single seam to send through: point it at a mailer later and nothing else
 * changes.
 */
export const RESET_TOKEN_TTL_MS = 24 * 60 * 60 * 1000

export function createResetToken(): { token: string; tokenHash: string; expiresAt: Date } {
  const token = crypto.randomBytes(32).toString('base64url')
  return {
    token,
    tokenHash: hashResetToken(token),
    expiresAt: new Date(Date.now() + RESET_TOKEN_TTL_MS),
  }
}

/** Only the hash is stored, so a database dump cannot be used to take accounts. */
export function hashResetToken(token: string): string {
  return crypto.createHash('sha256').update(token).digest('hex')
}

export function resetLinkFor(token: string, origin: string): string {
  const base = origin.replace(/\/+$/, '')
  return `${base}/?reset=${encodeURIComponent(token)}`
}

export type ResetRecord = { expiresAt: Date; usedAt: Date | null }

export function resetTokenProblem(record: ResetRecord | null, now = new Date()): string | null {
  if (!record) return 'That reset link is not valid.'
  if (record.usedAt) return 'That reset link has already been used.'
  if (record.expiresAt.getTime() <= now.getTime()) return 'That reset link has expired.'
  return null
}

/** Falls back to the request's own host so links work on any deployment URL. */
export function requestOrigin(headers: Record<string, string | string[] | undefined>): string {
  const first = (value: string | string[] | undefined) => (Array.isArray(value) ? value[0] : value)
  const forwardedHost = first(headers['x-forwarded-host']) || first(headers.host)
  const proto = first(headers['x-forwarded-proto']) || (process.env.VERCEL ? 'https' : 'http')
  if (!forwardedHost) return ''
  return `${proto}://${forwardedHost}`
}
